from tkinter import *
from tkinter import messagebox
a=Tk()
a.geometry("500x500")
a.title("student form")
l1=Label(a,text="Enter name",font="arial 18")
l1.grid(row=0,column=0,pady=10)
e1=Entry(a,font="arial 18")
e1.grid(row=0,column=1,pady=10)
l1=Label(a,text="Enter address",font="arial 18")
l1.grid(row=1,column=0,pady=10)
e1=Entry(a,font="arial 18")
e1.grid(row=1,column=1,pady=10)
l1=Label(a,text="Enter fees",font="arial 18")
l1.grid(row=2,column=0,pady=10)
e1=Entry(a,font="arial 18")
e1.grid(row=2,column=1,pady=10)
a.mainloop()
def ad():
    f=open('nn.txt','r')
    e1=e1.get()
    e2=e2.get()
    e3=e3.get()
    f.close()
